# Generated by Django 4.1.1 on 2022-10-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volume_jurtik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_nomor_issue', models.CharField(max_length=50)),
                ('judul', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jurnal_artikel_matematika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('nama_penulis', models.CharField(max_length=50)),
                ('tahun_publikasi', models.CharField(max_length=50)),
                ('volume_nomor_issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artikel.volume_jurtik')),
            ],
        ),
    ]
