# Generated by Django 4.1.1 on 2022-10-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submateri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_submateri', models.CharField(max_length=50)),
                ('materi', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Latihan_soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('penulis', models.CharField(max_length=50)),
                ('tanggal_rilis', models.DateField()),
                ('kode_submateri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='latihan.submateri')),
            ],
        ),
    ]
